curology/radiance-ui

- .gitignore
- docs/constants.md
- package.json
- src/constants/colors/index.js
- src/utils/index.js
- src/utils/isObject/index.js
- src/utils/isObject/test.js
- src/utils/throwOnUndefinedProperty/index.js
- stories/constants/Color.js
- stories/constants/index.js
- stories/constants/renderConstantsMap.js
Colors:
Not pretty, but a way to dynamically list all constant import names and key value pairs.
> Add constant stories and update colors

- docs/typography.md
- src/shared-components/typography/index.js
- src/utils/index.js
- src/utils/withDeprecationWarning/index.js
- src/utils/withDeprecationWarning/test.js
- stories/typography/index.js
Chatted with @benkolde regarding the naming and making it consistent.
Before, we were importing the typography components at the top level:
```jsx
import { ErrorText } from 'shared-components\typography';
<ErrorText>Error Message!</ErrorText>
```
However, now it's namespaced so we have more context AND we won't run into name collision issues
```jsx
import { Typography } from 'radiance-ui';
<Typography.Error>Error Message!</Typography.Error>
```
Also took care to not make any breaking changes until a major release version. Aka:
- Removed old usage from documentation but kept it in the code
- Added note to remove for next major
> rename some Typography components

- src/constants/breakpoints/index.js
- src/constants/index.js
- src/constants/mediaQueries/index.js
Didn't notice the breakpoints inside of the MEDIA_QUERIES constant was being exported and used in our main repo. This puts breakpoints in its own constant file so it's easier to import
Storybook automagically updated:
> move breakpoints into its own constant file

- .gitignore
- .storybook/webpack.config.js
- README.md
- babel.config.js
- package.json
- rollup.config.js
- yarn.lock
There were some issues on loading icons in storybook. This fixes the issue by removing `transform-svg-import-to-string` from babel config and adding a new rollup plugin that allows the ESM output to be compiled correctly without the babel plugin.
> Fix icon loading on Storybook + add readme

- README.md
Adding links to the documentation from the main front-page readme so that it's more clear where the documentation is, and easier to access them as well.  Fixes #9
> Adding in documentation links into the Readme file

- package.json
- rollup.config.js
- yarn.lock
There was an unused `url` plugin that was causing icons to be generated as urls (https://www.smooth-code.com/open-source/svgr/docs/rollup/#using-with-url-plugin) and causing the library to break on the consumer side. This patch removes the unused plugin and fixes the issue encountered on the consumer side
> [Alerts] Fix bundle for icons used in components

- src/shared-components/alert/index.js
`exit` function can be called from the duration expiration or onClick of the alert component. This prevents the `exit` function being called twice if onClick happens immediately right before the duration expires.
> [Alerts] Prevent calling exit multiple times

- docs/button.md
- docs/roundButton.md
- src/shared-components/accordion/index.js
- src/shared-components/button/components/roundButton/index.js
- src/shared-components/button/index.js
- src/shared-components/button/shared-components/loader/index.js
- src/shared-components/button/shared-components/loader/style.js
- src/shared-components/button/style.js
- stories/button/index.js
- Add Quinary button 
- Updated Button and Round Button stories
I also fixed the dot notation for the subcomponents in Accordion. 
Needed for welcome page design:
> add quinary button

- .eslintrc
- docs/immersiveModal.md
- docs/modal.md
- package.json
- src/constants/keycodes/index.js
- src/shared-components/immersiveModal/index.js
- src/shared-components/immersiveModal/style.js
- src/shared-components/immersiveModal/test.js
- src/shared-components/index.js
- src/shared-components/modal/index.js
- src/shared-components/modal/style.js
- src/shared-components/modal/test.js
- src/shared-components/offClickWrapper/index.js
- src/svgs/icons/index.js
- src/svgs/icons/menu-icon.svg
- src/utils/keyPressMatch/index.js
- stories/button/index.js
- stories/immersiveModal/defaultImmersiveModal.js
- stories/immersiveModal/index.js
- stories/modal/defaultModal.js
- stories/modal/index.js
- yarn.lock
Trello: https://trello.com/c/5arVBzoV
- Added Modal and ImmersiveModal (and necessary utils) to radiance library 
- Added MenuIcon to icon library
> added immersive and regular modals

- package.json
- src/shared-components/modal/index.js
In this PR
- move reference to `document` inside of component to fix gatsby build error
Problem:
Getting build error on Gatsby b/c `document` is not defined at build-time on Heroku.
Gatsby docs on issue -- they suggest moving the reference to `document` to a place that won't be called until `document` is defined:
https://www.gatsbyjs.org/docs/debugging-html-builds/
To fix this, moved the reference to the document inside the component so that `document` is defined by the time the reference is made.
> Modal gatsby patch

- jest.config.js
- package.json
- yarn.lock
Remote tests were failing due to an issue in Jest with the new Node version. They fixed it in this PR https://github.com/facebook/jest/pull/8050. This PR bumps Jest to latest v24
> upgrade jest to v24

- docs/immersiveModal.md
- src/shared-components/immersiveModal/index.js
- src/shared-components/immersiveModal/style.js
- stories/immersiveModal/defaultImmersiveModal.js
For the Change Plan modal in the Cancellation flow, the width has been set to 776px to match the new grid:
But the current immersiveModal's width is set to `${BREAKPOINTS.sm}px` which is `576px`
This PR adjusts the ImmersiveModal to allow for a `width` parameter of `small` (default) or `medium` to be passed in, with the `medium` option setting the modal to be `776px` wide.
> Adjust immersive modal to take width param

- docs/linkButton.md
- src/shared-components/button/components/linkButton/__snapshots__/test.js.snap
- src/shared-components/button/components/linkButton/index.js
- src/shared-components/button/components/linkButton/style.js
- src/shared-components/button/components/linkButton/test.js
- src/shared-components/button/index.js
- src/shared-components/button/style.js
- src/shared-components/index.js
- stories/button/index.js
You can now pass in React Router's `Link`/`NavLink` as a prop.
```jsx
import { Link } from 'react-router';
<LinkButton to="/somepath" renderedTag={Link}>
Click me!
</LinkButton>
```
> Add `<LinkButton>` to Radiance ✨

- src/shared-components/alert/index.js
- This adds `{...rest}` to `alert` so we can pass in arbitrary props. Useful for integration testing so we can add a `data-test-id`.
> Add rest to alert

- src/shared-components/loadingSpinner/__snapshots__/test.js.snap
- src/shared-components/loadingSpinner/index.js
- src/shared-components/loadingSpinner/style.js
- stories/carousel/index.js
- This can be considered as refactor to a  more html semantic version
- It was discovered in a bug for a gatsby build where the Spinner as a `<section>` was messing up the rendered layout when it has siblings `section` tags.
- https://trello.com/c/O1XyO0aW/478-bug-restricted-page-is-breaking-how-pages-render-after-auth-on-netlify
> Refactor LoadingSpinner: html semantic

- docs/tabs.md
- src/shared-components/index.js
- src/shared-components/tabs/index.js
- src/shared-components/tabs/style.js
- src/shared-components/tabs/test.js
- stories/tabs/TabsExample.js
- stories/tabs/index.js
- Similar to Form component this is the initial version compatible with PocketDerm. However:
- I dont like how it handle the Tabs as object {id,title}, worse it couples the initialTab to Id=1 forcing us to provide at least one Tab object with Id=1
- I propose drop the tab objects and just work with arrays of string titles and the active Id would be the index now. As usual this would require more refactor in PocketDerm as well.
> Tabs Component initial

- docs/transitions/fadeInContainer.md
- docs/transitions/opacityInAnimationStyle.md
- src/shared-components/index.js
- src/shared-components/transitions/__snapshots__/test.js.snap
- src/shared-components/transitions/index.js
- src/shared-components/transitions/style.js
- src/shared-components/transitions/test.js
- stories/transitions/index.js
- I combined both component from PocketDerm(FadeInContainer, OpacityInContainer) into only 1 since they were almost the same, except for the little slide animation added which I included as prop flag.
- I am not sure about `opacityInEffect` I included here to ease the refactor in PocketDerm, but I am open to suggestions since this is not a component, just a little style code shortcut. Maybe move somewhere in PocketDerm instead?
> Transition components

- src/shared-components/modal/index.js
- src/shared-components/modal/style.js
- I review the code in action (I am refactoring to Radiance modal in PocketDerm)and We need to revert back to its original for regarding Global style to prevent this issue
- The way The Radiance Modal is now does not work and do nothing: the style applied to ModalContainer does not reach the .ReactModalPortal element because they are disconnected in runtime (modal is created on the fly below in the dom tree)
- According to Emotion docs, the global style injection is harmless and unmounts when the component does so. I tested and the global style does not get injected multiple times when opening the modal more than once so there is no memory leaks: https://emotion.sh/docs/globals
> Modal global fix

- docs/button/roundButton.md
- src/shared-components/button/components/roundButton/index.js
- src/shared-components/button/components/roundButton/style.js
- src/shared-components/button/shared-components/loader/index.js
- src/shared-components/button/shared-components/loader/style.js
- src/shared-components/button/style.js
- src/shared-components/carousel/arrow/index.js
- src/shared-components/carousel/arrow/style.js
- src/shared-components/immersiveModal/index.js
- src/shared-components/immersiveModal/style.js
- src/shared-components/modal/index.js
- src/shared-components/modal/style.js
- stories/button/roundButton/index.js
In this PR:
- Added `action` option to buttonType prop
- Redesigned the docs 
- Ben I added `clickable` and `clickableHover` to the action button
- Make disabled and loading work for new action button
**NEW**
- Refactor Carousel/Modal/ImmersiveModal . to use this new `action` RoundButton
> Add "action" buttonType style to RoundButton

- docs/alert.md
- src/shared-components/alert/__snapshots__/test.js.snap
- src/shared-components/alert/index.js
- src/shared-components/alert/test.js
- stories/alert/index.js
`content` prop type is PropTypes.node so this component can accept any kind of content. This is implemented because of need to pass links inside alert component.
added custom prop check to make sure one of the props(text/content) is passed to component, this can be removed after text deprecation
added deprecationWarning for Alert component
updated alert.md with `content` prop
updated storied/alert with sample of alert component with `content` prop
> added `content` prop type to alert component

- docs/accordion.md
- src/shared-components/accordion/index.js
- src/shared-components/accordion/style.js
- stories/accordion/defaultAccordion.js
- stories/accordion/index.js
In this PR:
- Added an additional prop to Accordion for when the designs need the arrow to be flush on the right side of the accordion
> added accordion prop to right align the arrow

- src/constants/fonts/index.js
**What:**
This PR adds Apercu Mono in Radiance as a usable font. 
To use it in your projects you'll need to declare the font from `assets.curology...`
I may have done something wrong with this, so please tell me what to fix if I did! 
**Note:**
There is some custom styling that needs to happen at the larger text sizes with Apercu, it involves letter spacing but after talking to @daigof it seems like it would be best to just leave that up to each use case / instance for now.
> Add Apercu Mono as a usable font in Radiance

- docs/button/button.md
- docs/button/roundButton.md
- src/shared-components/button/__snapshots__/test.js.snap
- src/shared-components/button/components/roundButton/__snapshots__/test.js.snap
- src/shared-components/button/components/roundButton/index.js
- src/shared-components/button/components/roundButton/style.js
- src/shared-components/button/components/roundButton/test.js
- src/shared-components/button/index.js
- src/shared-components/button/shared-components/loader/index.js
- src/shared-components/button/shared-components/loader/style.js
- src/shared-components/button/style.js
- src/shared-components/button/test.js
- stories/button/button/index.js
- stories/button/roundButton/index.js
1. Corrects warnings logged in #124 related to passing non-boolean `loading` attribute to the DOM by renaming all usage in `<Button />` and `<RoundButton />` to `isLoading`. 
1. Adds a deprecation notice to use of `loading`
- Once this is merged in, I intend to release Radiance with a minor bump to update our emotion use. I'll then make the necessary changes in PocketDerm before then removing the deprecation warning. (Gatsby does not use this prop, though it looks like it is present in exactly one snapshot, due to it being a defaultProp).
> [Chore] Update button loading prop usage

- src/shared-components/optionButton/__snapshots__/test.js.snap
- src/shared-components/optionButton/style.js
**What**
@mvandy found an issue in the consult questionnaire that caused the option buttons to squish the checkmarks at smaller screen sizes / longer text blocks. 
This PR adds `flex: 0 0 auto;` to the component which will allow the checkbox / radio to retain its size. 
I haven't checked if this impacts production in any way. I can't imagine it would, but just thought I'd point that out.
> Fix option-button bug

- src/constants/colors/index.js
Our code comment indicating which color is tertiary does not match what is set as the tertiary color. This PR corrects it.
> [Patch] Set tertiary color to purple4 instead of purple10

- src/shared-components/dropdown/index.js
- src/shared-components/dropdown/mobileDropdown.js
- Part of https://app.asana.com/0/1130276194470636/1135497036319695/f
- In this case we are passing a default selected value that is also disabled
- In desktop works OK because is  custom  
- in mobile we have a `select` tag so when we try to select a disabled option it doesnt work and skip to the next undisabled value causing the bug
- This fix is smart enough that once you select a value, the previous default become disabled so you cannot go back and select that again
> Fix select dropdown on mobile with disabled default value as selected

- src/shared-components/accordion/index.js
This fixes a small issue where the Accordion wouldn't render open if the `isOpen` prop is initially `true`. 
We're using a `ref` to determine content height inside the accordion, but we were attempting to set the height before we had access to the node, thus it was still mounting as '0px'.
This PR waits for node availability and then updates the height in `componentDidMount`.
@heyamykate --  RE: [this PR](https://github.com/PocketDerm/PocketDerm/pull/6633) -- I think this is why the photo upload accordion originally had the `currentPerspective` set to null, then it would update on mount so the accordion would actually open. Right now, it loads as open but the content height is still set to '0px', so users need to click it twice to get it to expand.
> Update accordion to determine height after mount

- src/shared-components/button/components/linkButton/index.js
[`react-router-dom v5.1.0`](https://github.com/ReactTraining/react-router/releases/tag/v5.1.0) changes the `Link` component in such a manner that when we pass it as the `as` prop to `LinkButton` we get a prop type error, because it is no longer a `func` but rather an `elementType`.
> [Chore] Update LinkButton as prop option from func to elementType

- src/shared-components/optionButton/index.js
Updating the `subtext` proptype to `node`. 
I'm working on a design in which I need to use a component instead of a string.
> Allow node proptype for OptionButton subtext

- src/shared-components/immersiveModal/index.js
I'm building out a modal where I need to target the modal container so I can implement some scrolling functionality. I can't target the outer container because the scrolling context is on the modal container. This adds a `scrollContainerId` prop that will pass down an ID so we can access the context.
> Add tag ID prop to modal container

- src/shared-components/alert/index.js
Development logs a `setState` on unmounted component warning for all `Alerts` when we transition them off the screen.
I looked into it and this one-line change fixes the issue. I preferred the diff to using a callback in `setState` (e.g. `this.setState({ exited: true }, () => onExit({ ...rest }));`) to try and change behavior as little as possible.
> [Patch] Sequence onExit callback after setState in Alert component

- package.json
- yarn.lock
`serialize-javascript` has a vulnerability that is patched in `v2.1.1`. In order to remove all older versions of `serialize-javascript` from our `yarn.lock` file, this PR:
1. Updates `webpack` from `4.23.0` to `4.41.2`.
1. Removes unused `react-storybook-addon-chapters` dependency.
1. Reinstalls `rollup-plugin-size-snapshot@0.7.0` to update internal dependencies. 
1. Reinstalls `@storybook/react@~5.1.9` to update internal dependencies. 
See more details about the vulnerability here: https://github.com/advisories/GHSA-h9rv-jmmf-4pgx
> [Patch] serialize-javascript Vulnerability Fix

- src/shared-components/accordion/__snapshots__/test.js.snap
- src/shared-components/accordion/index.js
Asana: https://app.asana.com/0/1156933028783725/1156933028783728/f
After the icon updates, the chevron in the Accordion component appeared too small. Per Elijah, bumping its size to 16x16.
> [Icon Updates] Update accordion chevron

- .storybook/webpack.config.js
- docs/callout.md
- docs/chip.md
- docs/tooltip.md
- src/shared-components/button/__snapshots__/test.js.snap
- src/shared-components/button/components/linkButton/__snapshots__/test.js.snap
- src/shared-components/button/components/roundButton/__snapshots__/test.js.snap
- src/shared-components/button/style.js
- src/shared-components/chip/__snapshots__/test.js.snap
- src/shared-components/chip/index.js
- src/shared-components/chip/style.js
- src/shared-components/indicator/__snapshots__/test.js.snap
- src/shared-components/indicator/style.js
- src/shared-components/tooltip/__snapshots__/test.js.snap
- src/shared-components/tooltip/arrow.svg
- src/shared-components/tooltip/chevron-icon.svg
- src/shared-components/tooltip/index.js
- src/shared-components/tooltip/style.js
- stories/chip/index.js
- stories/tooltip/index.js
- **Buttons:** Update all buttons to have border radius: 4px.
- **Chip:** new styles, added default and secondary status. deprecated pending and closed status, but they will fallback to default styles if someone provides an incorrect status
-  **Tooltip:** update styles. Fixed arrow center positioning (now the arrow wont get in way of letters and is perfect centered). New `isSmall` prop for smaller tooltips.
- Callout: fixed doc to use 48x48 glyph
- Indicator: refactored to use same technique as chip using `display: inline-text` instead of `width:content-fit`
- Edit Storybook build (webpack config) that makes images broken. Compare Avatar component in PROD the images are all broken, this fixes that.
https://curology-radiance-pr-204.herokuapp.com/
> Update Components: Button, Chip and Tooltip

- src/shared-components/field/__snapshots__/test.js.snap
- src/shared-components/field/index.js
- src/shared-components/field/style.js
- I removed the SVG className selector in the previous [PR](https://github.com/curology/radiance-ui/pull/208/files) because I wasn't sure we needed it. I now remeber I specifically added that class a year ago while redesigning the field component for the first time and the reason was (is) to avoid leaking the styles to nested SVGs (see screenshot Checkbox icon is not showing due to this bug):
This PR restore the className selector to style only the SVG we want to target.
> [Hotfix] - SVG styles leaking outside Field component

- src/shared-components/tooltip/style.js
- I introduced this bug dont know how. Should be like before since I didn't work with the display prop, just reorder the props alphabetically
> [Hotfix] - Programatically display prop fix

- src/shared-components/indicator/__snapshots__/test.js.snap
- src/shared-components/indicator/style.js
- I made a change to display the Indicator same as Chips in this PR https://github.com/curology/radiance-ui/pull/204
- Reverting back to its original display mechanism since the Indicator is mostly used floating around and does not have to be displayed inline where it makes more sense with Chips
- Original mechanis is `width: content-fit` this is widely supported according to https://caniuse.com/#feat=mdn-css_properties_width_fit-content
> [Hotfix] - Indicator display style

- src/shared-components/verificationMessages/__snapshots__/test.js.snap
- src/shared-components/verificationMessages/index.js
- src/shared-components/verificationMessages/test.js
Currently passing a `messages` prop with an empty array to `VerificationMessages` causes a TypeError, i.e.
```jsx
<VerificationMessages messages={ { required: [] } } />
```
This PR adds a filter so we don't attempt to render empty arrays of messages.
See https://github.com/curology/PocketDerm/pull/8609#discussion_r404881354 for more info.
> Allow passing an empty array of messages to VerificationMessages

- src/.babelrc
- yarn.lock
Changes
**The SVG Bug was because** I was playing with latest packages last year (latest rollup, babel, etc) and got the lock file corrupted and seems I commited the package.json revert but not the yarn.lock change back.
`yarn.lock` Fix: I made 2 commits to this file: First one to restore the file to v6.4.1 The other one doing a fresh `yarn install` that updated the file itself with only new packages found in `package.json` like typescript and eslint rules
`@emotion/babel-preset-css-prop` must go to the end. [REFERENCE](https://www.npmjs.com/package/@emotion/babel-preset-css-prop)
> [Hotifx]- Svgr, rollup, yarn lock bug

- docs/alert.md
- src/shared-components/alert/index.js
- src/shared-components/alert/style.js
- src/shared-components/alert/test.tsx
- stories/alert/index.js
- To be more consistent whit our other flags usage it is best to place flags as true when you want to override some default behaviour so I changed the way we check the flag.
When you want full text scenario:
Before `<Alert truncateText={false} ...`
After `<Alert dontTrucateText ....`
This has no impact in Curology since the flag is not being used yet, I was motivated to do this because of the messy code I was doing in https://github.com/curology/PocketDerm/pull/8978 with truncateText={false}
> [Alerts] use dontTrucateText flag

- src/shared-components/selectorButton/__snapshots__/test.js.snap
- src/shared-components/selectorButton/index.js
- src/shared-components/selectorButton/test.js
- src/svgs/icons/circle-solid-icon.svg
- src/svgs/icons/index.js
A checkmark implies that the radio button can be unselected.  Radio
buttons cannot be unselected.  A white circle is a more consistent
pattern for radio buttons.
Checkboxes will still have a white checkmark.
Also, made some updates to pass the linter.
> Use circle icon for selected radio buttons instead of a checkmark

- yarn.lock
`yarn upgrade webpack`.  Storybook watching was breaking on later versions of
node because of compatibility issues with fsevents.  Upgrading webpack
fixes the issue so that watching mechanism is updated should fix it.
Note: webpack isn't actually upgraded.  Just it's dependencies
> Upgrade webpack

- docs/dropdown/main.md
- src/shared-components/dropdown/desktopDropdown.js
- src/shared-components/dropdown/index.js
- src/shared-components/dropdown/style.js
I noticed a bug where the dropdown max-height was rendering outside of its container, causing the last item to not be visible. 
Based on feedback, I added a `maxHeight` prop to the dropdown component to make it more flexible. 👍 
Before:
After:
> Update dropdown component max-height

- src/shared-components/accordion/thumbnails/index.tsx
We're enhancing the accessibility of our components. One item that came up in our audit was `Accordion.Thumbnail` images not having alt text. After some consideration I think that the thumbnail images are "decorative," especially in contrast to the other elements of the Accordion component, which require fully accessible functionality, rendering any pertinent alt text, at best, duplicative of the image (with also redundant alt text) contained in that aforementioned functionality.
This PR suppresses the error by setting an empty string. This is a small change, in any case, and this decision is not final, so it is subject to change with future changes/enhancements.
> [Accordion] Set decorative Thumbnail image alt text to empty string

- src/shared-components/button/__snapshots__/test.tsx.snap
- src/shared-components/button/components/linkButton/__snapshots__/test.tsx.snap
- src/shared-components/button/components/roundButton/__snapshots__/test.tsx.snap
- src/shared-components/button/style.ts
Keyboard navigation without focus state indication is difficult--adding this style will make things easier. This will apply to *all* buttons. 
I view this as a temporary solution--the outline on our primary buttons is very faint and not ideal, but it's a simple start.
> [a11y] Add box-shadow outline to button focus state

- .circleci/config.yml
- Adds corresponding `test-tsc` check to our CI build to check there are no TypeScript errors in our builds. 
- Renames `test` to `test-js` to clarify scope. 
- Once this is merged in I will update the repo settings to set `test-js` and `test-tsc` to `required`, and remove `required` from `test`.
> [TypeScript] Add CI Check

- src/shared-components/dropdown/desktopDropdown.tsx
I forgot to include the `aria-disabled` prop on the list element, which mean that we were seeing a color contrast violation for the disabled form elements. It also was unclear to the screen reader that the disabled options were actually disabled. I didn't catch this originally in the Storybook, because the text of the disabled example had the word "Disabled" in it, so the screen reader was announcing that it was a disabled element 😅 
Note that this is only required because we're stying an `li` to behave as a menu item. For any element that natively supports the `disabled` property, that is sufficient for the screen reader to interpret it properly and for `axe` to remove it from color-contrast checks.
> [a11y] Add aria-disabled to dropdown options

- src/shared-components/loadingSpinner/__snapshots__/test.js.snap
- src/shared-components/loadingSpinner/index.js
We put an id on the LoadingSpinner, but pages can have multiple LoadingSpinners, which violates the unique id rule. It doesn't look like we rely on this id for anything, so this PR removes it.
> [a11y] Remove id on LoadingSpinner

- src/shared-components/button/components/textButton/__snapshots__/test.tsx.snap
- src/shared-components/button/components/textButton/style.ts
I've updated most of our button stylings, but saw that our TextButton component has it's own stand-alone focus outline override. This PR adds the box-shadow we've been adding across components for keyboard navigation focus management. 
Andrew and Ben tagged as a general FYI
> [a11y] Add box-shadow to TextButton

- package.json
- src/shared-components/dialogModal/index.tsx
- src/shared-components/dialogModal/style.ts
- yarn.lock
[Asana Task](https://app.asana.com/0/1182623358122135/1182893274583740)
When the `DialogModal` is open, we should lock the focus inside of the modal to make it easy for keyboard users to interact with. This PR accomplishes this by using the [FocusScope](https://react-spectrum.adobe.com/react-aria/FocusScope.html) component from react-aria. We automatically trap focus inside the modal when it opens, and return focus to the last focused element when it closes. In addition, if a close icon is present, we allow the user to dismiss the modal using the Escape key.
> [a11y] Trap keyboard focus in DialogModal

- src/shared-components/accordion/__snapshots__/test.tsx.snap
- src/shared-components/accordion/index.tsx
- src/shared-components/accordion/style.ts
[Asana Task](https://app.asana.com/0/1182623358122135/1182893274583743)
In this PR:
* Adds a keyDown listener so that you can expand or close the Accordion using the Enter key
* Provides tabIndex, role, and our custom focus state to the Accordion title to make the button focusable
* Uses `aria-expanded`, `aria-disabled`, and `aria-hidden` to provide additional info to screen readers and to ensure that disabled components will not raise color-contrast issues
> [a11y] Add keyboard control to Accordion component

- CHANGELOG.md
- docs/checkbox.md
- src/shared-components/checkbox/index.js
- src/shared-components/selectorButton/__snapshots__/test.js.snap
- src/shared-components/selectorButton/index.js
- src/shared-components/selectorButton/style.js
- stories/checkbox/index.js
This PR adds a disabled prop to the Checkbox component and disables the checkbox when this prop is true by changing the background color of it and preventing the user from clicking the checkbox. This is needed more immediately for the CCPA Opt Out project.
Note: This is no longer needed for the CCPA Opt Out project (we decided to use a button instead), but I might as well still publish this in Radiance since I did the work for it.
> Add disabled prop to Checkbox component

- src/shared-components/dropdown/desktopDropdown.tsx
- src/shared-components/dropdown/test.tsx
After upgrading to the WCAG 2.1 standard in our Cypress test, there was an issue raised with the dropdown component's aria-label. The 2.1 standard includes a rule that the text of an element should be contained within the `aria-label` https://dequeuniversity.com/rules/axe/3.5/label-content-name-mismatch?application=axeAPI The `aria-label` I was using on the component was too generic. I tested this using a screen reader and actually found that it worked well without the `aria-label`, because the `role` and `haspopup` attributes made it reasonably clear the intention. More user testing would be required to be sure, but for now I'd rather have less `aria` information than incorrect information. 
In addition, I removed the `id` from the Dropdown. There are some places where we render multiple …
> [a11y] Fix dropdown aria-label and ID

- CHANGELOG.md
- docs/carousel.md
- src/shared-components/carousel/__snapshots__/test.tsx.snap
- src/shared-components/carousel/arrow/__snapshots__/test.tsx.snap
- src/shared-components/carousel/arrow/index.tsx
- src/shared-components/carousel/arrow/style.ts
- src/shared-components/carousel/arrow/test.tsx
- src/shared-components/carousel/index.tsx
- src/shared-components/carousel/style.ts
- src/shared-components/carousel/test.tsx
- stories/carousel/index.js
The [new LP pricing module](https://www.notion.so/curology/Pitch-New-Landing-Page-Pricing-Module-412f1153db264ea8a1d33c7416aa56d1) has a different positioning for the carousel arrows. They are aligned beneath the carousel cards on the bottom right side. The coloring of the arrows is also a bit different. Because this component will only be used in the pricing module on the site, rather than creating a new `arrowColor` prop, I just added both of these things (new alignment and new coloring) as a `bottomRightAlignedArrows` prop to the Radiance Carousel component.
> Update Carousel component to have bottom right aligned arrows

- src/constants/boxShadows/index.ts
- src/shared-components/carousel/arrow/__snapshots__/test.tsx.snap
- src/shared-components/container/__snapshots__/test.tsx.snap
- src/shared-components/dropdown/__snapshots__/test.tsx.snap
- src/shared-components/dropdown/desktopDropdown.tsx
- src/shared-components/dropdown/index.tsx
- src/shared-components/dropdown/mobileDropdown.tsx
- src/shared-components/dropdown/style.ts
- src/shared-components/dropdown/test.tsx
- src/shared-components/optionButton/__snapshots__/test.tsx.snap
1. Updates our `clickable` and `clickableHover` styles to match what design has in Figma. 
1. Updates our `border-radius` styling for the Dropdown component, which previously had no `border-radius`.
- Our Mobile dropdown will always have `border-radius: 4px` since we rely on native select dropdown for functionality. 
- Our Desktop dropdown will have `border-radius: 4px` *unless* it is open, at which point the following occurs:
- The Dropdown select will have `border-radius: 4px 4px 0 0`, shorthand for setting the top-left and top-right border radius.
- The last child of the Dropdown options will have `border-radius: 0 0 4px 4px`, shorthand for setting the bottom-left and bottom-right border radius. 
1. Updates our Dropdown component to accept an optional `borderRadius` prop, so that the …
> [Dropdown] Apply box-shadow changes 

- src/shared-components/optionButton/__snapshots__/test.tsx.snap
- src/shared-components/optionButton/index.tsx
- src/shared-components/optionButton/style.ts
This PR adds `border-radius: 4px` by default to our `OptionButton`.
#338 updated the `box-shadow` styling that applies to this component, so the requirement of updating the `box-shadow` styling is already satisfied.
**Before**:
**After**:
> [Option Button] Add 4px border-radius

- src/shared-components/dropdown/index.tsx
#338 renamed the prop spreading from `props` to `rest`, but because of how we were destructuring the props (e.g. `Dropdown = (props) => {}`, which then destructured in the body) I accidentally removed how we were passing down `options` to the `DesktopDropdown` component. (You can test this live on http://radiance-ui.curology.com/, the desktop dropdown has no options). 
I had actually been previously under the impression that we could spread additional properties to `DesktopDropdown` but not `MobileDropdown`, but checking the definition of `DesktopDropdown` it's clear there's no prop spreading in place, so we can be specific with the props we pass down to it. 
This PR restores the `DesktopDropdown` functionality.
> [Bugfix] Restore DesktopDropdown Options Prop Threading

- .eslintrc
- package.json
- src/constants/boxShadows/index.ts
- src/shared-components/accordion/__snapshots__/test.tsx.snap
- src/shared-components/accordion/style.ts
- src/shared-components/button/__snapshots__/test.tsx.snap
- src/shared-components/button/components/linkButton/__snapshots__/test.tsx.snap
- src/shared-components/button/components/roundButton/__snapshots__/test.tsx.snap
- src/shared-components/button/style.ts
- src/shared-components/carousel/arrow/__snapshots__/test.tsx.snap
- src/shared-components/dropdown/__snapshots__/test.tsx.snap
- src/shared-components/dropdown/desktopDropdown.tsx
- src/shared-components/dropdown/style.ts
- src/shared-components/dropdown/test.tsx
- src/shared-components/tabs/style.js
- src/utils/injectGlobalStyles/style.ts
- src/utils/styles/buttonReset.ts
- stories/dropdown/mobileExample.js
- yarn.lock
This PR adds two new properties to our `BOX_SHADOWS` constants:
1. `focus`
1. `focusInner`. 
The behavior of `focus` is two separate box-shadows to simulate an outline with margin between the element and the outline. Here is the change of behavior in the `Button` component:
Before:
After:
The behavior of `focusInner` is an `inset` box-shadow, such that the desired outline appears within the given element. Here is the change of behavior in the `Accordion` component:
Before:
After:
This PR also adds a polyfill for `focus-visible`, a CSS pseudo-class that effectively allows us to apply custom styling to keyboard navigation that does not take effect for mouse navigation. ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible)). This allows us to more gracefully introduce …
> [a11y] Update focus states

- docs/banner.md
- docs/immersiveModal.md
- package.json
- src/constants/boxShadows/index.ts
- src/shared-components/banner/__snapshots__/test.tsx.snap
- src/shared-components/banner/index.tsx
- src/shared-components/banner/style.ts
- src/shared-components/banner/test.tsx
- src/shared-components/button/components/textButton/__snapshots__/test.tsx.snap
- src/shared-components/button/components/textButton/style.ts
- src/shared-components/dialogModal/style.ts
- src/shared-components/field/__snapshots__/test.js.snap
- src/shared-components/field/style.js
- src/shared-components/immersiveModal/crossIconComponent/index.tsx
- src/shared-components/immersiveModal/index.tsx
- src/shared-components/immersiveModal/style.ts
- src/shared-components/optionButton/__snapshots__/test.tsx.snap
- src/shared-components/optionButton/style.ts
- src/shared-components/selectorButton/__snapshots__/test.js.snap
- src/shared-components/selectorButton/style.js
- stories/banner/index.tsx
- stories/immersiveModal/immersiveModalExamples.tsx
This PR contains the final changes made to our accessibility/keyboard focus states before cutting a major release. Many of changes are simply replacing `BOX_SHADOWS.focusSecondary` for `BOX_SHADOWS.focus` and then updating the snapshots. The below notes cover the other changes:
1. Remove `BOX_SHADOWS.focusSecondary`
- `BOX_SHADOWS.focus` and `BOX_SHADOWS.focusInner` will be the preferred focus states going forward. 
1. Makes `Banner` a button instead of div. 
- `Banner` optionally accepts an `onClick` prop. When it is present, we'll make it keyboard focusable. Otherwise, we'll treat it as a div. (No interactivity.)
- Removes `defaultProps` in favor of ES6 defaults. 
1. Converts `src/shared-components/immersiveModal/index.tsx` to a function component.
- If we want to keep the diff smaller, …
> [a11y] Other Focus States

- src/shared-components/field/__snapshots__/test.tsx.snap
- src/shared-components/immersiveModal/index.tsx
- src/shared-components/verificationMessages/index.tsx
- Modal: this is pending fixes explained here: https://app.asana.com/0/1173345595414308/1197707937611097/f   
- VerificationMessages: While updating Radiance in Curology, I was checking the snapshot differences and something didnt look right. So I tested the email field in the login page comparing side y side with Production (old radiance) and noticed the initial error animation was lost. Bug was introduced here: https://github.com/curology/radiance-ui/pull/421/files#diff-e9498b132d50a72d80dfb59c0cc8e675150eaeb28909ea7819c319d3f10f8756. If no error messages I returned null but we need the Transition structure present for the inital animation to work. So this fix revert back that functionality to the way it was in the old JS file.
BUG no animation
FIX animation restored
> [Hotfixes] -  Verification messages animation and modal

- .circleci/config.yml
- package.json
- stories/carousel/index.stories.tsx
I got a little too cute by adding `master` to the `skip` glob in the `chromatic` build script. This PR updates the logic to account for [the squash merge creating a new git commit](https://www.chromatic.com/docs/ci#github-squash-rebase-merge-and-the-master-branch), which means we just need to auto-accept the `master` build changes when they happen.
> [Chromatic] Reconfigure master build logic

- README.md
Chromatic has upped our repo from the Free plan to the Open Source Free Plan, so let's thank them in our README!
Changing the org name from `PocketDerm` to `curology` broke the CircleCI badge, so this PR also fixes it.
> [README] Add Chromatic Callout and Fix CircleCI Badge

- package.json
- src/constants/colors/primary.ts
- src/constants/colors/secondary.ts
- Adds `'transparent'` to our theme colors to support consumer app usage, OK'd by design.
> [Colors] Add 'transparent' color

- src/shared-components/immersiveModal/index.tsx
Fixes error in consumer app when non-string is used for title:
> [ImmersiveModal] Fix PropTypes

- .size-snapshot.json
- src/icons/icons/svgs/Arrow.tsx
- src/shared-components/tooltip/__snapshots__/test.tsx.snap
- src/svgs/icons/arrow.svg
context #579
I branched that of secondary-theme PR so it was not clean this merges to master directly, besides I removed one unnecessary class in the svg path
> Fix Arrow svg to support theme

- src/shared-components/field/style.ts
https://www.notion.so/curology/Input-fields-Review-disabled-text-instances-40622fc9f7d64e47833267d8c57b207c
This should not have any impact in primaryTheme since the color value is the same for tint3 and textDisabled
After Fix:
> [Theme] - Fix field placeholder color for secondary theme

- src/constants/typography/index.ts
- src/constants/typography/primaryTypography.ts
- src/constants/typography/secondaryTypography.ts
- src/shared-components/typography/index.ts
- Secondary Theme button should have larger font (`14px` vs. `12px`).
- Secondary Theme button should have no `font-weight` application (default is `bold`).
> [Theming] Adjust Secondary Theme Button Styling

- src/shared-components/tabs/style.ts
Updates the inactive usage. Same value for Primary theme but achieves parity for Secondary theme:
> [Theming] Replace primaryTint3 with textDisabled in Tab

- .size-snapshot.json
- src/shared-components/typography/index.ts
- src/utils/injectGlobalStyles/style.ts
We use `larssiet` for all the `styles` in `src/shared-components/typography/index.ts`. However, we want to use a different font for `Display`, `Heading`, and `Title` for our secondary theme:
These changes set the `font-family` on the class, giving it higher precedence than `body`. 
This also removes the direct `TYPOGRAPHY_CONSTANTS` import in `injectGlobalStyles`, which has no impact on output.
> [Theming] Apply distinct secondary Display, Heading, and Title font

- .size-snapshot.json
- src/shared-components/accordion/thumbnails/style.ts
- src/shared-components/button/shared-components/container/index.ts
- src/shared-components/field/style.ts
- src/shared-components/tooltip/style.ts
We have some instances of in-lining `css` serialization within other `css` serializations and `styled` serializations, which are unnecessary and contribute to bundle size bloat, particularly in our Tooltip component. 
Removing them in favor of plain string in-lining results in an overall ~5.1% reduction in gzip size and ~12.1% reduction in minified size in the `radiance-ui` package.
> [Styling] Remove Superfluous css Serialization to Reduce Size

- src/shared-components/button/style.ts
- src/shared-components/field/style.ts
- src/shared-components/optionButton/style.ts
- src/shared-components/toggle/style.ts
- src/shared-components/typography/index.ts
- src/shared-components/verificationMessages/style.ts
- src/utils/themeStyles/index.ts
1. Sets `line-height: 1.4` across all applicable `line-height` stylings.
- Exceptions are of the type like the Dropdown `line-height`, which is set to a very large value to center the text. 
1. Removes `bold` font-weight from secondary header components (display/h1, heading/h2, title/h3).
Release as patch version in consumer apps, but also we're at the point where we should add visual regression testing for our secondary theme, too. So I will open up that PR as well.
> [Theming] Modify Secondary Theme line-height and font-weight

- src/shared-components/indicator/__snapshots__/test.tsx.snap
- src/shared-components/indicator/index.tsx
- src/shared-components/indicator/style.ts
- src/shared-components/indicator/test.tsx
- stories/indicator/index.stories.tsx
This PR updates `<Indicator />` to include a `backgroundColor` prop to allow the component to be reused for purposes outside of messages and notifications. 
Other: the border-radius has been hardcoded to 50% in order to show the component consistently between the primary and secondary themes.
> [Components] Add background color to Indicator component

- src/shared-components/avatar/__snapshots__/test.tsx.snap
- src/shared-components/avatar/style.ts
This updates the `background-color` of the Avatar component to use `secondaryTint1` rather than `secondary`.
> Update theme of background-color on Avatar component to secondaryTint1

- src/shared-components/typography/index.ts
Undoes the `labelStyle` portion of the changes in #704 for better compat.
> [Theming] Hard-code label line-height for focus state compatibility

- src/constants/themes/types.ts
- src/shared-components/dialogModal/__snapshots__/test.tsx.snap
- src/shared-components/dialogModal/index.tsx
- src/shared-components/dialogModal/style.ts
- src/shared-components/dialogModal/test.tsx
- src/tests/testingLibraryHelpers.tsx
- stories/dialogModal/index.stories.tsx
Exposes a prop, `modalColor`, for the `DialogModal` component. This prop allows us to specify the background color of the modal. Currently, we are limited it to the theme's `background` color.
This change is necessitated by a [new design](https://www.figma.com/file/6QekjeGkdl6PUKNcdQA9mc/CS-and-provider-messages-workload-tweaks?node-id=54%3A0) for the "New Message" prompt in the patient dashboard.
I wasn't able to verify within the app via `yarn link` due to some [puzzling JS errors](https://curology.slack.com/archives/CU02B06GY/p1613010943108300), but Storybook looks 👍 to me.
To review the new stories in Chromatic, looks like I need to log in. Is this an IT helpdesk request? I don't see any Chromatic credentials in 1Password's Engineering vault.
> Add ability to change DialogModal background color

- src/constants/typography/primary.ts
- src/constants/typography/secondary.ts
- src/shared-components/button/components/anchorLinkButton/__snapshots__/test.tsx.snap
- src/shared-components/button/components/anchorLinkButton/index.tsx
- src/shared-components/button/components/anchorLinkButton/style.ts
- src/shared-components/button/components/anchorLinkButton/test.tsx
- src/shared-components/button/index.tsx
- src/shared-components/dialogModal/style.ts
- src/shared-components/immersiveModal/style.ts
- src/shared-components/index.ts
- src/shared-components/typography/index.ts
- stories/button/anchorLinkButton/index.stories.tsx
1. This PR adds a new component, `AnchorLinkButton`, to match the spec of our Figma design for buttons that look like links:
Here is the Review App story: https://curology-radiance-pr-778.herokuapp.com/?path=/story/components-button-anchorlinkbutton--default
This component does not currently exist in `radiance-ui`. Moreover, attempts to approximate this design using our existing `TYPOGRAPHY_STYLE.link` styling **do not match this spec**. It applies `border-bottom` rather than `text-decoration: underline`, among other things. We've started [surfacing issues around text placement between the two brands](https://github.com/curology/radiance-ui/pull/720#discussion_r568047415), and it seems ideal to rely on CSS to avoid more pixel displacement as we seek out solutions for those discrepancies. …
> [Theme] [Components] Add AnchorLinkButton, update TYPOGRAPHY_STYLE.link

- src/shared-components/callout/index.tsx
- src/shared-components/callout/style.ts
- stories/callout/index.stories.tsx
Some of our components have a `*type` paradigm that allows us to set specific styling properties, primarily our Buttons (`primary`/`secondary`/`tertiary`/`quaternary`).
This PR adds a `success` type to our Callout component--which pulls in our `success` and `successBackground` colors--to style the Callout. We do not expose styling of the component generally, and rather than overhaul the API to allow any set of colors, this PR prefers the course of adding specific presets for consistency in use. (We can also test here whether any combination is inaccessible, for which the `'success'` preset passes our built-in accessibility add-on).
Design:
Story:
This PR adds a Storybook story for this version in order to test it via Chromatic, rather than add unit tests.
> [Callout] Adds new 'success' type

- package.json
- yarn.lock
These were errantly added. They are part of `essentials`. I think there was, in part, old dependabot config that got it added back.
> [Dependencies] Remove errantly added @storybook dependencies

- src/shared-components/accordion/thumbnails/style.ts
- src/shared-components/button/components/anchorLinkButton/style.ts
- src/shared-components/button/index.tsx
- src/shared-components/button/style.ts
- src/shared-components/chip/style.ts
- src/shared-components/field/style.ts
- src/shared-components/index.ts
- src/shared-components/indicator/style.ts
- src/shared-components/optionButton/style.ts
- src/shared-components/tabs/style.ts
- src/shared-components/typography/index.ts
- src/shared-components/verificationMessages/style.ts
Recently we adopted a pattern of always exporting type definitions so they could be used in consumer applications. However, since we were naming the exports in our actual exports file, none of those definitions were being exported from the same namespace, so importing the type definitions required deeply nested paths (e.g. `import type { ChipProps } from 'radiance-ui/lib/shared-components/chip';`). 
This PR exports everything exported from the component definition files so we have access to the TypeScript types as well. 
TODO: Make it impossible for folks to import exports from `style` files to avoid unintended use of Design System.
> [TypeScript] Export Type Definitions

- src/shared-components/button/index.tsx
- src/shared-components/callout/index.tsx
- src/shared-components/optionButton/index.tsx
We sometimes pass in `false` which is a valid `node` type (and the offending component is written in JS, not TS) when we really should be passing in `null` or `undefined`.
> [Bugfix] Add additional false check to icon props

- .storybook/preview.tsx
- src/shared-components/accordion/index.tsx
- src/shared-components/alert/style.ts
- src/shared-components/banner/style.ts
- src/shared-components/button/components/anchorLinkButton/style.ts
- src/shared-components/button/components/linkButton/index.tsx
- src/shared-components/button/components/linkButton/style.ts
- src/shared-components/button/components/roundButton/index.tsx
- src/shared-components/button/constants.ts
- src/shared-components/button/shared-components/loader/index.tsx
- src/shared-components/button/shared-components/loader/style.ts
- src/shared-components/button/style.ts
- src/shared-components/callout/index.tsx
- src/shared-components/carousel/style.ts
- src/shared-components/chip/index.tsx
- src/shared-components/loadingSpinner/index.tsx
- src/shared-components/loadingSpinner/style.ts
- src/shared-components/progressBar/style.ts
- src/shared-components/selectorButton/style.ts
- src/shared-components/typography/index.ts
- src/types/@emotion/styled/index.ts
- src/types/emotion-theming/index.ts
- src/utils/injectGlobalStyles/style.ts
- src/utils/themeStyles/index.ts
- stories/button/index.stories.tsx
- stories/button/linkButton/index.stories.tsx
- stories/button/roundButton/index.stories.tsx
- stories/container/index.stories.tsx
- stories/loadingSpinner/index.stories.tsx
- stories/progressBar/index.stories.tsx
Will clean up the diff in #903, and appears to potentially be required for next-gen tooling like ESBuild: https://github.com/storybookjs/storybook/pull/14380/files
> [TypeScript] Use type-only import syntax

- src/shared-components/container/index.ts
- src/shared-components/container/style.ts
- src/shared-components/optionButton/style.ts
#903 removed most of our `export const` declarations in `style.ts` files, but it looks like I missed a few (besides the `button` ones purposefully left that way). This updates that.
> [Components] Remove lingering style exports

- src/shared-components/accordion/index.tsx
- src/shared-components/accordion/style.ts
- src/shared-components/optionButton/index.tsx
- src/shared-components/optionButton/style.ts
Our components allow string literal union props for border radius, but these are not theme-aware, meaning a theme that generally has no border-radius will not raise an error if we pass in a `'32px'` border-radius, for example.
This PR modifies the props to allow only the keys present in `theme.BORDER_RADIUS`, so that usage will also conform with that given theme.
> [Theme] Update Component Border Radius Props

- .storybook/preview-head.html
- stories/theme/fonts.stories.tsx
1. Updates our `theme.FONTS` story to show bold and italic versions of the different fonts.
Before (only shows actual values, nothing visual):
After:
___
2. Fixes how we're setting up our `quadrant-text` fonts with italics. `font-style: italic` should be used so that when there are italics on the page, the correct font is requested. If this isn't set up correctly, the browser tries its best to approximate an italic font on its own.
Before:
After:
You'll also notice that fetching the italic font also means we're rendering the actual font we want to for the `quadrant-text` fonts:
Without change:
With change:
The true italic font is much more elegant than the Browser approximation, which mostly just applies some slant to the base font. 
Investigate & update our `grey-ll` usage to match this …
> Update Agency Fonts + Story

- src/shared-components/dialogModal/index.tsx
PropTypes are particular about distinguishing between `null` and `undefined`. This will prevent errors in consumer app usage when the function is not provided, updating the default value `undefined` to be `null`.
> [DialogModal] Type Refinement

- babel.config.js
We have an emotion 10 --> 11 branch ready for release but there's a bit of a size regression, ~+2.7% in bundle size. I've identified some change in `style.js` output as partially responsible:
Emotion 10:
```tsx
var Container = _styled("div", {
target: "ei8l98n0",
label: "Container"
})(...rest)
```
Emotion 11 (before this PR):
```tsx
var Container = _styled("div", process.env.NODE_ENV === "production" ? {
target: "ei8l98n4"
} : {
target: "ei8l98n4",
label: "Container"
})(...rest)
```
Emotion 11 (with 5b34e62):
```tsx
var Container = _styled("div", {
target: "ei8l98n4",
label: "Container"
})(...rest)
```
Unless the `autoLabel` default value changed, which I didn't notice in the migration guide, I'm not sure why this behavior is different. In any case it helps shave down about 33% of the …
> [Emotion] Prefer autoLabel: true for output

- jest.config.js
- src/shared-components/immersiveModal/style.ts
- src/shared-components/tooltip/__snapshots__/test.tsx.snap
- src/shared-components/tooltip/index.tsx
- src/shared-components/tooltip/style.ts
Roughly ~7kb of the Emotion regression is due to our including a `<Global />` style in Tooltip. This PR:
1. Removes that style, as well as the manual `document.body.classList` handling.
1. Adds `onClick` functionality to the TooltipBox
1. Updates the styling to prevent (intended) behavior regression. 
Before: The click behavior applies `cursor-pointer` to the body so the `cursor: pointer` still shows even after the tooltip is closed:
https://user-images.githubusercontent.com/13544620/120420148-66c20980-c329-11eb-8bca-b7a9130b8e12.mov
After: Behavior is simplified and fixed:
https://user-images.githubusercontent.com/13544620/120420168-70e40800-c329-11eb-8e6e-49d4a7286664.mov
After making this change the Bundlewatch reports a small size increase in the `next` branch now: `(+2.92KB, -1.46KB, …
> [Tooltip] Modify Hover Logic

- src/utils/index.ts
This is necessary to use the themes, so we need to export it. We're using 'deep imports' from the filesystem at the moment to access them.
Longer term since we're always passing these in to the `Global` component, should we export a component instead? I.e.
```jsx
// in Radiance
export BrandStyles = <Global<ThemeType> styles={brandStyles} />;
export ResetStyles =  <Global styles={resetStyles} />;
// in the consumer
const Layout = ({ children }: LayoutProps) => (
<>
<ResetStyles />
<BrandStyles />
<MainContainer id="main-container">
<PageContainer>{children}</PageContainer>
</MainContainer>
</>
);
```
> Export `injectGlobalStyles`

- .gitignore
- CHANGELOG.md
- bundlewatch.config.json
- package.json
- rollup.config.js
- src/tests/README.md
- src/types/README.md
- tsconfig.json
My last release broke Type resolution 😢
TypeScript cannot parse conditional exports, so it's unable to resolve types for paths like `radiance-ui/lib/constants` if they're actually in `radiance-ui/dist/constants`. Using the same name for the built assets ensures TypeScript can resolve the path correctly without having to parse the conditional exports.
We _could_ build the types to `lib` and the bundles to `dist` but that seemed confusing.
See https://github.com/microsoft/TypeScript/issues/33079
> Move built assets from dist to lib

- src/types/global.d.ts
- src/utils/shouldShowForEnvironment/index.ts
Using the bracket syntax can cause issues with various tools that try to statically replace the environment variables like Next.JS and Vite. The dot syntax is easier to replace when the app is built.
The brackets were used to make TypeScript happy, so we can tell TypeScript that we expect the value to exist instead.
For more info:
https://vitejs.dev/guide/env-and-mode.html#production-replacement
https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables
> Access NODE_ENV with dot operator

- src/shared-components/dropdown/desktopDropdown.tsx
- src/shared-components/dropdown/index.tsx
- src/shared-components/dropdown/mobileDropdown.tsx
This PR continues the work of #1110 by adding an optional id prop so that we can associate `<label for="unique-field-identifier" />` with the Dropdown by passing the id to it, e.g. `<select id="unique-field-identifier" />`. We previously removed ID in #307 because it was not unique, but this ID is meant to be used in conjunction with our existing form components. 
Future PRs can look into more robust a11y handling via `react-aria` and consideration of orchestrating certain prop configurations as non-optional so as to raise type errors in accordance with a11y errors.
> [Dropdown] Add optional id prop

- src/icons/glyphs/cleanserGlyph.ts
This PR adds `CleanserGlyphSecondary` to the CleanserGlyph export.
> [Glyphs] Update CleanserGlyphSecondary

- src/shared-components/segmentedControl/__snapshots__/test.tsx.snap
- src/shared-components/segmentedControl/index.tsx
- src/shared-components/segmentedControl/style.ts
- src/shared-components/segmentedControl/test.tsx
- src/shared-components/segmentedControl/types.ts
- stories/field/index.stories.tsx
- stories/segmentedControl/index.stories.tsx
1. Run `eslint --fix` to address new standards since branch was created.
1. Replace `80px` `border-radius` with `theme.BORDER_RADIUS.large`.
- It is accurately `0` for the secondary theme, and it is `32px` for the primary theme, which is equal to `80px` (you can edit in your dev tools to examine this.)
1. Update `transition: transform 0.22s` to `transition: transform 0.3s` to match `300ms` specified in Figma spec: <img width="310" alt="Screen Shot 2021-09-24 at 12 24 01 AM" src="https://user-images.githubusercontent.com/13544620/134617962-875a2d46-dee8-405c-9827-70f3481c4ccd.png">
1. Move `border` style from item container to individual segment items to prevent issue of `Indicator` being presentationally different from the other segment items.
- Before: <img width="520" alt="Screen Shot …
> [SegmentedControl] Refinements

- yarn.lock
Review apps and builds appear to be breaking and it is possibly because the frozen lockfile does not match what it should.
> Yarn.lock cleanup

- .circleci/config.yml
- package.json
Heroku review apps have been broken since mid-October (!). The culprit appears to be a our lax `engines.node` settings, which means Heroku has been running `node` v17 and appears to be incompatible with part of our toolchain. This PR sets it to 16, and updates CircleCI, to match what most folks are running locally. TODO: Make this more specific with something like NVM.
https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
Sets `yarn` to v1 explicitly even though Heroku defaults to v1.
> [CircleCI] [Heroku] Configure package.json#engines with more specificity

- .github/dependabot.yml
The config in `.github/dependabot.yml` is a little outdated because it includes old `@dependabot ignore` directives that no longer apply. 
This PR also adds more code comments for context around why some dependencies are ignored entirely.
> [Dependabot] Update Config

- src/shared-components/globalStyles/style.ts
The color on inputs were showing up as blue on IOS 15 devices because Apple introduced a default color to all inputs. This sets our own default color so the inputs don't fallback to the IOS default.
> Update default input color

- package.json
I bumped node to 16 to resolve some Heroku build issues in #1283 but broke downstream v14 usage in our consumer apps. This PR will unbreak that behavior.
> [Hotfix] Allow node 14 in package.json#engines

- src/shared-components/dialogModal/index.tsx
- src/shared-components/immersiveModal/index.tsx
- src/shared-components/offClickWrapper/index.tsx
React 17 changed some event propagation behavior: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#fixing-potential-issues
This PR fixes the usage of `OffClickWrapper` in `ImmersiveModal`: right now, the behavior is that when the modal is initiated, the offClickWrapper click close event immediately fires, so we see no content. 
It also updates some `ref` handling in `useEffect` as outlined here: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#potential-issues
> [Bugfix] ImmersiveModal and OffClickWrapper

- src/shared-components/tabs/index.tsx
We are often executing conditional logic based on the values of the tabs and so we want type information that is stronger than just `number` or `string`.
> [TypeScript] Use Generics with Tabs TabType Definition

- src/shared-components/tabs/index.tsx
`tabItems` must be `readonly` for `as const` compatibility.
> [TypeScript] Updates Tabs TabGeneric Definition

- .circleci/config.yml
- src/shared-components/dropdown/desktopDropdown.tsx
- src/shared-components/dropdown/index.tsx
- src/shared-components/dropdown/mobileDropdown.tsx
- src/shared-components/dropdown/test.tsx
- stories/dropdown/index.stories.tsx
This PR exposes the `onFocus` event from the underlying elements of the `Dropdown` component.
**Use case**
We would like to instrument an analytics event when a user focuses on the dropdown to observe interaction behavior. We can derive certain observations like "Users who at least focused the dropdown in this form were 50% less likely to bounce" or "30% of users focused on this dropdown, but only 50% of those who focused ultimately made a selection".
> Add onFocus prop to Dropdown

- src/shared-components/icon/index.tsx
- src/utils/themeStyles/index.ts
The Tertiary Theme is built specifically to cater to the Admin+Pharmacy Apps in PocketDerm. While this will be further extended in the future - the current scope of the theme is to establish Admin/Pharmacy-specific typography+fonts & inherit all remaining assets from the Primary Theme (following suit with current usage on Timeline).
This ticket is a minor fix for an oversight in conditional rendering for Icons and certain minor styles. With these condition updates - the Admin/Pharmacy Apps will be injected with the proper inheritance of Primary Theme assets.
Note - v26.4.0 has not yet been deployed to PocketDerm; current changes for this version are not yet visible on production. To be released with the merge of [MPO 921](https://github.com/curology/PocketDerm/pull/17146)
> Update Theming Conditions to include Tertiary Theme

- src/shared-components/optionButton/__snapshots__/test.tsx.snap
- src/shared-components/optionButton/index.tsx
This PR adds `aria-checked` to the `optionButton` component. This allows screen-readers to indicate whether a checkbox or radio-button is checked/selected.
**Before**
**After**
> [a11y] Add aria-checked to OptionButton

- src/shared-components/field/__snapshots__/test.tsx.snap
- src/shared-components/field/index.tsx
- src/shared-components/verificationMessages/__snapshots__/test.tsx.snap
- src/shared-components/verificationMessages/index.tsx
The `Field` component does not currently indicate a failure/invalid state to screen-readers. This PR addresses this issue by adding an `output` element to `VerificationMessages` and adding an [aria-invalid](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-invalid) state to the input field.
---
https://user-images.githubusercontent.com/83731749/174132070-79126982-ce24-47ca-a0fc-a7e15a979f9f.mov
> [a11y] Add screen reader indicator for invalid input

- src/shared-components/callout/__snapshots__/test.tsx.snap
- src/shared-components/callout/index.tsx
- src/shared-components/callout/style.ts
- src/shared-components/callout/test.tsx
- stories/callout/index.stories.tsx
This PR adds a close (X) icon to the top-right corner of the callout component. This can be done by adding the new `onClose` function prop to the callout component.
This is my first PR in this repo, so looking for any and all feedback. Thank you.
> Adds close (X) icon to callout component.

- package.json
- src/shared-components/dialogModal/__snapshots__/test.tsx.snap
- src/shared-components/dialogModal/index.tsx
- src/shared-components/dialogModal/style.ts
- src/shared-components/dialogModal/test.tsx
- src/shared-components/immersiveModal/index.tsx
- stories/dialogModal/index.stories.tsx
- yarn.lock
- Adds @react-aria/dialog package in order to use `useDialog` hook so that screen readers can announce that the user is in a modal
- Adds `useDialog` hook to both `ImmersiveModal` and `DialogModal`
- Renames `onCloseIconClick` to `onClick` in `DialogModal` and makes this property required
- Updates tests
- Updates the `DialogModal` in storybook (since props changed)
- Removes duplicate documentation now that close icon is default
> [og-387] [og-388] update radiance modal components to use react-aria

- src/constants/colors/primary.ts
Currently `secondaryTint3` & `secondaryTint4` are defined as the same color. This PR updates `secondaryTint4` to align with our radiance colors as defined in [Figma](https://www.figma.com/file/dE10QHEwFYEqb2cMLrHev0ce/Radiance-Colors?node-id=0%3A1).
**Before**
**After**
> [SEO-124] Update secondaryTint4 color

- src/shared-components/optionButton/style.ts
This pr decreases the width of `OptionButton`s that contain images to `151px` and adds `margin-left` to the `TextContainer`.
> Meron/minor OptionButton style updates

- src/shared-components/optionButton/index.tsx
- src/shared-components/optionButton/style.ts
- stories/optionButton/index.stories.tsx
Discussed with Adam and we decided it best to add a border back to the `OptionButton` component for consistency reasons and Agency compatibility. Adding the border back in revealed `border-radius` discrepancies between `ImageContainer` and 'Image` so adjustments there are also added as part of this pr (before and after shown below).
> meron/add border and update border-radius of OptionButton

- src/shared-components/optionButton/index.tsx
- src/shared-components/optionButton/style.ts
- stories/optionButton/index.stories.tsx
This pr updates the `border-radius` for the `Image` styled component on `OptionButton`.  Previously, the `border-radius` on the `Image` was being applied to Agency because we weren't using `Theme`
> meron/update OptionButton component border radius

- src/shared-components/tooltip/index.tsx
- stories/tooltip/index.stories.tsx
Currently, the tooltip will open either by clicking or hovering over the trigger when on desktop. On mobile, the tooltip opens only on click. This PR introduces the option to disable the hover behavior, such that the tooltip will only open on click for both mobile & desktop.
> Add disableHover prop to Tooltip component
