docs/radioButton.md
src/constants/boxShadows/index.js
src/shared-components/index.js
src/shared-components/radioButton/__snapshots__/test.js.snap
src/shared-components/radioButton/index.js
src/shared-components/radioButton/style.js
src/shared-components/radioButton/test.js
stories/alert/index.js
stories/radioButton/index.js

This PR adds the `<RadioButton />` component as is on the master design system sketch file.
Sketch file:
Storybook: https://curology-radiance-pr-26.herokuapp.com/?selectedKind=RadioButton&selectedStory=Usage&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs

[RadioButton] Add `<RadioButton />` component, test, story & documentation

---

docs/accordion.md
src/shared-components/accordion/__snapshots__/test.js.snap
src/shared-components/accordion/index.js
src/shared-components/accordion/style.js
src/shared-components/accordion/test.js
src/shared-components/accordion/thumbnails/index.js
src/shared-components/accordion/thumbnails/style.js
src/shared-components/index.js
stories/accordion/defaultAccordion.js
stories/accordion/index.js

Trello: https://trello.com/c/S0ijYQ8O/261-move-accordion-to-radiance
Moving accordion to radiance from shared-components

added accordion to radiance

---

babel.config.js
docs/button.md
docs/roundButton.md
jest.config.js
package.json
src/shared-components/button/__snapshots__/test.js.snap
src/shared-components/button/components/roundButton/__snapshots__/test.js.snap
src/shared-components/button/components/roundButton/index.js
src/shared-components/button/components/roundButton/style.js
src/shared-components/button/components/roundButton/test.js
src/shared-components/button/index.js
src/shared-components/button/shared-components/container/index.js
src/shared-components/button/shared-components/loader/index.js
src/shared-components/button/shared-components/loader/style.js
src/shared-components/button/style.js
src/shared-components/button/test.js
src/shared-components/index.js
stories/button/index.js
tests/__mocks__/svgMock.js
yarn.lock

This PR adds the `<Button />` and `<RoundButton />` components. Each one has:
- Component
- Tests
- Readme
- Story
[Button Story](https://curology-radiance-pr-33.herokuapp.com/?selectedKind=Buttons&selectedStory=Button&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)
[RoundButton Story](https://curology-radiance-pr-33.herokuapp.com/?selectedKind=Buttons&selectedStory=RoundButton&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)

Add `<Button />` and `<RoundButton />`

---

src/shared-components/selectorButton/__snapshots__/test.js.snap
src/shared-components/selectorButton/index.js

Fix console warning

---

.eslintrc
.storybook/config.js
docs/typography_style.md
package.json
src/shared-components/accordion/style.js
src/shared-components/accordion/thumbnails/style.js
src/shared-components/alert/__snapshots__/test.js.snap
src/shared-components/alert/index.js
src/shared-components/alert/style.js
src/shared-components/button/__snapshots__/test.js.snap
src/shared-components/button/components/roundButton/__snapshots__/test.js.snap
src/shared-components/button/components/roundButton/index.js
src/shared-components/button/components/roundButton/style.js
src/shared-components/button/shared-components/container/index.js
src/shared-components/button/shared-components/loader/style.js
src/shared-components/button/style.js
src/shared-components/chip/style.js
src/shared-components/container/style.js
src/shared-components/immersiveModal/style.js
src/shared-components/modal/style.js
src/shared-components/selectorButton/__snapshots__/test.js.snap
src/shared-components/selectorButton/style.js
src/shared-components/typography/index.js
src/utils/icons/index.js
src/utils/icons/style.js
src/utils/injectGlobalStyles/index.js
stories/constants/Color.js
stories/icons/style.js
yarn.lock

Trello: https://trello.com/c/KuLojsv2
Updating Radiance to use Emotion 10. This will be a major version bump to V2 when published, as it is a breaking change. 
Also created a `Radiance_V1` branch for updates to V1, to be maintained until our app is also updated to Emotion 10. 
Docs: https://github.com/emotion-js/emotion/blob/master/docs/migrating-to-emotion-10.md

Emotion 10

---

docs/loadingSpinner.md
src/shared-components/index.js
src/shared-components/loadingSpinner/__snapshots__/test.js.snap
src/shared-components/loadingSpinner/index.js
src/shared-components/loadingSpinner/style.js
src/shared-components/loadingSpinner/test.js
stories/loadingSpinner/index.js

In this PR:
- Adds LoadingSpinner component and story

added loadingSpinner to library

---

README.md

revert changes

---

src/shared-components/typography/index.js

This wasn't working properly for some reason

fix body style for emotion 10

---

src/svgs/icons/index.js
src/svgs/icons/minus-icon.svg

Added a minus icon for use in the two-week checkin flow.

Added minus icon

---

src/svgs/icons/equals-icon.svg
src/svgs/icons/index.js

Added equals icon for use in checkin flows.

Added equals icon.

---

src/shared-components/modal/style.js

- Update the padding for modals so there isn't so much whitespace

Update modal padding per design's suggestion

---

.eslintrc
.prettierrc
docs/tooltip.md
src/shared-components/index.js
src/shared-components/tooltip/__snapshots__/test.js.snap
src/shared-components/tooltip/index.js
src/shared-components/tooltip/style.js
src/shared-components/tooltip/test.js
stories/tooltip/index.js

- Complete tooltip with docs and demo with knobs
- added eslint rule to prevent error in tests files
- added prettierrc rules to standard format on editor

New Tooltip Component

---

CHANGELOG.md
package.json

- Create changelog entry
- Update new version references

New tooltip component - Published Version

---

src/constants/colors/index.js
src/shared-components/alert/__snapshots__/test.js.snap
src/shared-components/alert/style.js
src/shared-components/banner/__snapshots__/test.js.snap
src/shared-components/banner/style.js
src/shared-components/button/__snapshots__/test.js.snap
src/shared-components/button/components/linkButton/__snapshots__/test.js.snap
src/shared-components/button/components/roundButton/__snapshots__/test.js.snap
src/shared-components/button/shared-components/loader/style.js
src/shared-components/button/style.js
src/shared-components/chip/__snapshots__/test.js.snap
src/shared-components/chip/style.js
src/shared-components/dropdown/__snapshots__/test.js.snap
src/shared-components/dropdown/style.js
src/shared-components/immersiveModal/style.js
src/shared-components/tooltip/__snapshots__/test.js.snap
src/shared-components/typography/index.js

- task: https://trello.com/c/mSqJr1Ch/89-update-colors
- I tested the deprecation warning and works, but we may need to review the message: `[Deprecation Warning]: purple60 will be deprecated in v2. Use purple70 instead`
is it correct?

Colors adjustments

---

docs/bulkErrors.md
src/shared-components/bulkErrors/formatError/index.js
src/shared-components/bulkErrors/index.js
src/shared-components/bulkErrors/style.js
src/shared-components/field/__snapshots__/test.js.snap
src/shared-components/field/index.js
src/shared-components/field/style.js
src/shared-components/field/test.js
src/shared-components/index.js
src/utils/helperTransition/index.js
stories/bulkErrors/index.js

- Added Bulk error component
- Refactor Field to use the new BulkeError

New bulk errors components

---

docs/progressBar.md
src/constants/index.js
src/constants/progressBarStatus/index.js
src/shared-components/index.js
src/shared-components/progressBar/__snapshots__/test.js.snap
src/shared-components/progressBar/index.js
src/shared-components/progressBar/style.js
src/shared-components/progressBar/test.js
stories/progressBar/index.js

- Refactored/CleanedUp version of what we found in `jsx/components` in PocketDerm

New ProgressBar component

---

docs/optionButton.md
src/shared-components/index.js
src/shared-components/optionButton/__snapshots__/test.js.snap
src/shared-components/optionButton/index.js
src/shared-components/optionButton/style.js
src/shared-components/optionButton/test.js
stories/optionButton/index.js
stories/optionButton/optionButtonExample.js

- New component based on 
- https://trello.com/c/8aMso8zr/74-convert-option-button-component
- https://trello.com/c/gbkdYruo/88-update-option-buttons-to-new-specs
- compatible with pocketderm version . but completely redesigned

New optionButton component

---

src/shared-components/optionButton/__snapshots__/test.js.snap
src/shared-components/optionButton/style.js
stories/optionButton/index.js

- Hotfix to be compatible with PocketDerm, it makes sense otherwise they will look all stacked in curology.

Add margin bottom to the Option Button

---

docs/field.md
src/shared-components/field/__snapshots__/test.js.snap
src/shared-components/field/index.js
src/shared-components/field/style.js
stories/field/index.js

- Mostly ErrorIcon styles
- required to merge the fixes for Fields in PocketDerm

Fixes for Form Fields components

---

docs/optionButton.md
src/shared-components/optionButton/__snapshots__/test.js.snap
src/shared-components/optionButton/index.js
src/shared-components/optionButton/style.js
stories/optionButton/index.js
stories/optionButton/optionButtonExample.js

- Added Subtext and examples for Option Button
- Modified Interactive Example to match design example provided

Option button subtext

---

src/shared-components/optionButton/__snapshots__/test.js.snap
src/shared-components/optionButton/style.js

- Option Button Fixed Secondary style: only when selected

OptionButton: Fix secondary color

---

src/svgs/icons/calendar-icon.svg
src/svgs/icons/index.js

Added calendar icon to radiance.

Calendar icon

---

src/constants/spacing/index.js
src/utils/withDeprecationWarning/index.js
stories/constants/renderConstantsMap.js

- also fixed a map key prop warning in constants story.

Add Deprecation warning for SPACING

---

.circleci/config.yml
CHANGELOG.md
README.md
package.json
yarn.lock

Standing on the shoulders of giants.

v2.1.0 - Add CircleCI

---

src/constants/boxShadows/index.js
src/shared-components/alert/__snapshots__/test.js.snap
src/shared-components/banner/__snapshots__/test.js.snap
src/shared-components/container/__snapshots__/test.js.snap
src/shared-components/dropdown/__snapshots__/test.js.snap
src/shared-components/optionButton/__snapshots__/test.js.snap
src/shared-components/tooltip/__snapshots__/test.js.snap

**What is this:** 
Updating the hex code associated with the `box-shadow` color which will change our `box-shadows` to be aligned with what's reflected in Figma. The hex codes matches our `primary` color which will add a blue hue to the shadows.
**Before:** 
**After:**

Update Shadow Colors

---

CHANGELOG.md

Once merged I will release via npm.
- Update deprecation notice warnings ([PR #127](https://github.com/PocketDerm/radiance-ui/pull/127))
- **BREAKING**: Remove Alert component text prop code ([PR #126](https://github.com/PocketDerm/radiance-ui/pull/126))
- Update Button and RoundButton loading prop usage ([PR #125](https://github.com/PocketDerm/radiance-ui/pull/125))
- Update emotion dependency usage ([PR #124](https://github.com/PocketDerm/radiance-ui/pull/124))
- Add Apercu Mono font in monoFont declaration ([PR #123](https://github.com/PocketDerm/radiance-ui/pull/123))
- Update box-shadow color ([PR #122](https://github.com/PocketDerm/radiance-ui/pull/122))

CHANGELOG - v4.0.0

---

src/shared-components/immersiveModal/index.js

- Needed to send custom styles to immersive modal

Add rest params to immersive modal

---

src/shared-components/button/__snapshots__/test.js.snap
src/shared-components/button/components/linkButton/__snapshots__/test.js.snap
src/shared-components/button/components/roundButton/__snapshots__/test.js.snap
src/shared-components/button/style.js
src/shared-components/selectorButton/__snapshots__/test.js.snap
src/shared-components/selectorButton/style.js

Asana: https://app.asana.com/0/1156933028783725/1156933028783730/f
In this PR:
- Update the border-width on the base-button styles
- Update border-width on base selector button (used by checkboxes and radios)
- Update test snapshots

Update button borders

---

src/shared-components/optionButton/__snapshots__/test.js.snap
src/shared-components/optionButton/style.js

Asana: https://app.asana.com/0/1156933028783725/1156933028783730/f
Missed the option button when updating the border width of the buttons and checkboxes 🤦‍♀ 
In this PR
- Update border width of OptionButton
- Update jest snapshots

[Button Borders] Update border width of option button

---

docs/alert.md
src/shared-components/alert/__snapshots__/test.tsx.snap
src/shared-components/alert/index.js
src/shared-components/alert/style.js
src/shared-components/alert/test.tsx
stories/alert/index.js

- https://app.asana.com/0/1126113002004936/1172672399123690/f
- enabled by default, may be disabled per specific case

[Alert component] add truncateText prop

---

package.json

https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
Will release as v8.

Add tree-shaking capabilities

---

src/shared-components/accordion/index.tsx
src/shared-components/alert/index.tsx
src/shared-components/button/index.tsx
src/shared-components/callout/index.tsx
src/shared-components/carousel/arrow/index.tsx
src/shared-components/carousel/index.tsx
src/shared-components/checkbox/index.tsx
src/shared-components/chip/index.tsx
src/shared-components/dialogModal/index.tsx
src/shared-components/offClickWrapper/index.tsx
src/shared-components/progressBar/index.tsx
src/shared-components/radioButton/index.tsx
src/shared-components/selectorButton/index.tsx
src/utils/helperTransition/index.tsx

- Convert Carousel,DialogModal and OffClickWrapper to FC
- Other Minor ordering stuff. There will be a final PR part 3 that cover all the Alphabetically Ordering and all checks of Props and Refactor of Colors constants usage

[Cleanup] - Part 2

---

.size-snapshot.json
package.json

[Hotfix] CJS Build

---

src/shared-components/dialogModal/__snapshots__/test.tsx.snap
src/shared-components/dialogModal/index.tsx
src/shared-components/dialogModal/style.ts
src/shared-components/dialogModal/test.tsx
src/shared-components/immersiveModal/index.tsx
src/shared-components/immersiveModal/style.ts
src/shared-components/immersiveModal/test.tsx
stories/dialogModal/index.stories.tsx
stories/immersiveModal/index.stories.tsx

- updated doc
- Stories: refactor naming in DialogModal WithColor: refactor name and remove closeIcon logic since that has its own story

[Modals] - refactor out Paragraphs styling in Modals

---

src/shared-components/dialogModal/__snapshots__/test.tsx.snap
src/shared-components/dialogModal/style.ts
src/shared-components/immersiveModal/__snapshots__/test.tsx.snap
src/shared-components/immersiveModal/style.ts
src/shared-components/immersiveModal/test.tsx

Made overlay Theme aware. Approved by Ben.

[Modals] - Update overlay color for both modals

---

.circleci/config.yml
.eslint.tsconfig.json
.lintstagedrc.js
jest.config.js
stories/tsconfig.json
tsconfig.json

Surfaced in #550, want to reduce that diff and try and resolve some CI errors with a new merge commit

[Misc] Code Cleanup

---

.eslintrc
package.json
src/shared-components/alert/hooks.ts
src/shared-components/alert/index.tsx
src/shared-components/button/shared-components/loader/style.ts
src/shared-components/carousel/index.tsx
src/shared-components/chip/index.tsx
src/shared-components/dropdown/test.tsx
src/shared-components/optionButton/style.ts
src/shared-components/tooltip/index.tsx
src/utils/helperTransition/index.tsx
stories/constants/availableConstants.stories.tsx
stories/field/index.stories.tsx
stories/icons/index.stories.tsx
yarn.lock

Will help us keep code complexity in check, mostly.

[ESLint] Add eslint-plugin-sonarjs

---

src/constants/index.ts
src/constants/portals/index.ts
src/shared-components/dialogModal/index.tsx
src/shared-components/immersiveModal/index.tsx
src/tests/testingLibraryHelpers.tsx
stories/constants/availableConstants.stories.tsx

We use some magic strings, this PR moves it into a constant and imports it.

[Modals] Use constant portal id

---

src/shared-components/immersiveModal/__snapshots__/test.tsx.snap
src/shared-components/immersiveModal/index.tsx

Fixes `Buttons must have discernible text` issue

[ImmersiveModal] Add aria-label to CrossIconButton

---

src/shared-components/carousel/arrow/__snapshots__/test.tsx.snap
src/shared-components/carousel/arrow/index.tsx

We can expose it as a prop if there arises a need in the future.

[Accessibility] Add aria-label to Carousel Arrow button component

---

src/shared-components/chip/index.tsx
stories/chip/index.stories.tsx

GE-746 required a new style of chip. Style info was taken from Figma and should match current styles

GE-746: Adding info styling for chip

---

package.json

Because it apparently matters if default is last...

[ARCH-930]: Update export order
